#source: https://github.com/ChristianLempa/videos/blob/main/nextcloud-tutorial/docker-compose.yml
version: "3"
volumes:
  nextcloud-data:
  nextcloud-db:
  npm-data:
  npm-ssl:
  npm-db:
  coredns:

services:
  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=r3pl4c3
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=r3pl4c3
      - MYSQL_PASSWORD=r3pl4c3
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud


  npm-app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      - DB_MYSQL_HOST=npm-db
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=npm
      - DB_MYSQL_PASSWORD=r3pl4c3
      - DB_MYSQL_NAME=npm
    volumes:
      - npm-data:/data
      - npm-ssl:/etc/letsencrypt

  npm-db:
    image: jc21/mariadb-aria:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=r3pl4c3
      - MYSQL_DATABASE=npm
      - MYSQL_USER=npm
      - MYSQL_PASSWORD=r3pl4c3
    volumes:
      - npm-db:/var/lib/mysql


  coredns:
    image: coredns/coredns
    command: -conf Corefile
    ports:
      - "53:53"
      - "9153:9153"
    volumes:
    - ./coredns:/data:ro
  #source: https://github.com/omawhite/coredns-docker-compose/tree/master